sudo: required

dist: trusty

services:
  - docker

language:
  - go

go:
  - '1.14'
  - '1.15'

git:
  depth: 1

install: true # skipping the default go dependencies install step

script:
  - bash integration_test.sh
